version: '3'
services:
  pio-template:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Working
      - ..:/workspaces/pio-template:cached
      # device access
      - /dev:/dev
    working_dir: /workspaces/pio-template
    tty: true
    command: sleep inf
    # device access
    privileged: true
